//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by 2DSim.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MY2DSIM_DIALOG              102
#define IDR_ACCELERATOR                 102
#define IDR_MAINFRAME                   128
#define IDD_USER_CONFIGURATION          131
#define IDB_BITMAP_CC                   133
#define IDB_BITMAP_UPCC                 134
#define IDB_BITMAP_DN                   135
#define IDB_BITMAP_DNCC                 136
#define IDB_BITMAP_DNUP                 137
#define IDB_BITMAP_DNUPCC               138
#define IDB_BITMAP_UP                   139
#define IDR_ACCELERATOR1                140
#define IDD_HIDE_UNHIDE                 141
#define IDD_DIALOG_JUMP                 143
#define IDD_LOAD                        144
#define IDD_DLG_FLOOR_CONFIG            146
#define IDD_SELECT_ALGORITHM            149
#define IDC_BUTTON1                     1002
#define IDC_BUTTON_OPEN_TRAFFIC         1002
#define IDC_BUTTON_FLIGHT_TIME          1002
#define IDC_BUTTON_MANUAL_DISPATCH      1002
#define IDC_BUTTON2                     1003
#define IDC_BUTTON_USER_CONFIGURATION   1003
#define IDC_BUTTON_DWELL_TIME           1003
#define IDC_BUTTON_AUTOMATIC_DISPATCH   1003
#define IDC_BUTTON_REG_CANCEL_TIME      1004
#define IDC_BUTTON_OPEN_PERFORMANCE_REPORT 1005
#define IDC_1D                          1005
#define IDC_BUTTON_NEXT_EVENT           1006
#define IDC_2D                          1006
#define IDC_EDIT1                       1007
#define IDC_BUTTON_NEXT_PASSENGER       1007
#define IDC_EDIT_FLOORCOUNT             1007
#define IDC_EDIT_EXPLANATION            1007
#define IDC_EDIT2                       1008
#define IDC_STATIC_CURRENT_TIME         1008
#define IDC_EDIT3                       1009
#define IDC_STATIC_PASSENGER_INFO       1009
#define IDC_EDIT_LOBBY_FLOOR            1009
#define IDC_EDIT4                       1010
#define IDC_SPIN1                       1010
#define IDC_BUTTON_ADD_MOVE             1010
#define IDC_EDIT5                       1011
#define IDC_EDIT_CAPACITY               1011
#define IDC_EDIT_RELEASE                1011
#define IDC_BUTTON_JUMP                 1011
#define IDC_RICHEDIT_DEBUG              1012
#define IDC_EDIT06                      1012
#define IDC_EDIT_CARS                   1012
#define IDC_EDIT_I_DIRECTION            1012
#define IDC_EDIT7                       1013
#define IDC_BUTTON_NEXT_NEW_HCALL       1013
#define IDC_EDIT_ACCELERATION           1013
#define IDC_EDIT_I_DELAY                1013
#define IDC_EDIT8                       1014
#define IDC_EDIT_VELOCITY               1014
#define IDC_EDIT_R_DIRECTION            1014
#define IDC_EDIT05                      1015
#define IDC_EDIT9                       1015
#define IDC_EDIT_JERK                   1015
#define IDC_EDIT_R_DELAY                1015
#define IDC_EDIT_OPENING_TIME           1016
#define IDC_EDIT_CLOSING_TIME           1017
#define IDC_EDIT00                      1017
#define IDC_EDIT01                      1018
#define IDC_EDIT_OPENING_TIME2          1018
#define IDC_EDIT_START_DELAY            1018
#define IDC_EDIT02                      1019
#define IDC_EDIT_FLOOR_OFFSET           1019
#define IDC_EDIT03                      1020
#define IDC_EDIT_ADJACENT_LIMIT         1020
#define IDC_EDIT04                      1021
#define IDC_EDIT_CLOSING_TIME2          1021
#define IDC_EDIT_STOP_DELAY             1021
#define IDC_EDIT07                      1022
#define IDC_EDIT_HOISTWAYS              1022
#define IDC_CHECK_OVERHEAD              1023
#define IDC_CHECK_PIT                   1024
#define IDC_STATIC_DEBUG                1025
#define IDC_CHECK_MSG_DISABLE           1025
#define IDC_EDIT_CAR                    1026
#define IDC_EDIT_MINIMUM_DIST           1026
#define IDC_EDIT_DESTINATION            1027
#define IDC_EDIT_INITIATE               1028
#define IDC_EDIT_TIME                   1029
#define IDC_EDIT_I_BASIS                1029
#define IDC_BUTTON_SAVE                 1030
#define IDC_EDIT_INDEX_PASSENGER        1030
#define IDC_EDIT_I_THRESHOLD            1030
#define IDC_CHECK_REASSIGN              1031
#define IDC_BUTTON_LOAD                 1031
#define IDC_EDIT_I_RELATIVITY           1031
#define IDC_CHECK_HOLD_DOOR_OPEN        1032
#define IDC_EDIT_R_BASIS                1033
#define IDC_EDIT_R_THRESHOLD            1034
#define IDC_RADIO_JUMP_TIME             1035
#define IDC_EDIT_R_RELATIVITY           1035
#define IDC_RADIO_JUMP_PASSENGER_INDEX  1036
#define IDC_LIST_WARNING                1037
#define IDC_BUTTON_CLEARWARNING         1038
#define IDC_BUTTON_FLOOR_CONFIG         1039
#define IDC_MSFLEXGRID1                 1040
#define IDC_COMBO_DUTY                  1040
#define IDC_EDIT_TMP                    1041
#define IDC_CHECKNULL                   1042
#define IDC_CHECKH                      1043
#define IDC_CHECKC                      1044
#define IDC_CHECKD                      1045
#define IDC_CHECKHC                     1046
#define IDC_CHECKHD                     1047
#define IDC_CHECKHCD                    1048
#define IDC_CHECKCD                     1049
#define IDC_CHECK_MOTION_HARD           1050
#define IDC_BUTTON_INITIALIZEDLL        1051
#define IDC_CHECK_REOPEN                1051
#define IDC_DETACH_DLL                  1052
#define IDC_CHECK_COGS_SPY              1052
#define IDC_LIST_ALGORITHM              1053
#define IDC_DWELL_TIME_AVOID_CONDITIONAL_STOP 1053
#define IDC_RUN_DELAY_AVOID_CONDITIONAL_STOP 1054
#define IDC_DISPATCH_STATE              1055
#define IDC_ABOUT_DESCRIPTION           1056
#define IDC_REDUCE_PROFILE              1056
#define IDC_VERSION                     1057
#define IDC_VERSION_INFO                1058
#define IDC_COMBO_DWELL_TYPE            1059
#define IDC_EXECUTABLE_TYPE             1060
#define IDC_CHECK_HEXECUTER             1061
#define IDC_HOISTWAYDLL                 1062
#define IDC_CHECK_HOISTWAYMANAGER       1062
#define IDC_CHK_HM                      1063
#define IDC_STATIC_CLOSEST_MARGIN       1066
#define IDC_BUTTON_CAR0                 1100
#define IDC_BUTTON_CAR1                 1101
#define IDC_BUTTON_CAR2                 1102
#define IDC_BUTTON_CAR3                 1103
#define IDC_BUTTON_CAR4                 1104
#define IDC_BUTTON_CAR5                 1105
#define IDC_BUTTON_CAR6                 1106
#define IDC_BUTTON_CAR7                 1107
#define IDC_OPEN_BATCH                  32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1067
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
