/*-------------------------------------------------------------- %BMH% --
| File Name: switch.h - Project specific compilation switches.
|
| Description:
|  This file contains compilation switches specific to a project.
|  This file, as it exists in the reuse library, should be used as an
|  example/skeleton only. The user should make a copy of this file,
|  include it as part of the project library, and tailor it to the specific
|  needs of the project.
|
|     SCN       Date    Who      Description
| -----------  ------  -----     -------------------------------------------
| AAA30xxxAAA  960931  BA/SH/MR  Initial Creation
|
|  Copyright (C) 1996 Otis Elevator. All Rights Reserved.
---------------------------------------------------------------- %EMH% --*/
#ifndef switch_DEFINED             // for multiple includes

/*-----------------------------------------------------------------------
|  Define compiler dependent switches.
-------------------------------------------------------------------------*/
// #define  MSC
//#define MT68K_C
#define DCC68K

/*-----------------------------------------------------------------------*/
#define switch_DEFINED
#endif
